const webkit = [
'webkitRTCPeerConnection',
'webkitMediaStream',
'webkitURL',
'webkitRequestAnimationFrame',
'webkitCancelAnimationFrame',
'webkitStorageInfo',
'webkitSpeechGrammar',
'webkitSpeechGrammarList',
'webkitSpeechRecognition',
'webkitSpeechRecognitionError',
'webkitSpeechRecognitionEvent',
'webkitRequestFileSystem',
'webkitResolveLocalFileSystemURL',
]